// React/src/components/NewContact.js
import React, {Component} from 'react';
import axios from 'axios';
import SimpleReactValidator from 'simple-react-validator';
import moment from 'moment';
import Global from '../Global';
import { Navigate } from 'react-router-dom';

class NewContact extends Component{

    url = Global.url;

    nombreRef = React.createRef();
    apellidosRef = React.createRef();
    movilRef = React.createRef();
    direccionRef = React.createRef();
    poblacionRef = React.createRef();
    cPostalRef = React.createRef();
    provinciaRef = React.createRef();
    emailRef = React.createRef();
    fNacimientoRef = React.createRef();

    state = {
        provinces: [],
        contact: {f_nacimiento: moment().format('YYYY-MM-DD')},
        status: null
    }

    constructor(){

        super();
        this.validator = new SimpleReactValidator(
            {
                autoForceUpdate: this,
                className: 'msg-validator',
                messages: {
                    required: 'El :attribute es requerido.',
                    email: 'El :attribute debe ser un email válido.'
                },
                validators: {
                    c_postal: {
                        message: 'El :attribute debe ser un código postal válido.',
                        rule: (val, params, validator) => {
                            return validator.helpers.testRegex(val,/^(5[0-2]{1}|[0-4]{1}\d{1})\d{3}$/) && params.indexOf(val) === -1
                        },
                        required: true
                    },
                    movil: {
                        message: 'El :attribute debe ser un número de móvil válido.',
                        rule: (val, params, validator) => {
                            return validator.helpers.testRegex(val,/^[6|7]{1}[0-9]{8}$/) && params.indexOf(val) === -1
                        },
                        required: true
                    }
                }
            }

        );

    }

    componentDidMount(){

        this.getProvinces();

    }

    changeState = () => {

        this.setState({

            contact: {

                nombre: this.nombreRef.current.value,
                apellidos: this.apellidosRef.current.value,
                movil: this.movilRef.current.value,
                direccion: this.direccionRef.current.value,
                poblacion: this.poblacionRef.current.value,
                c_postal: this.cPostalRef.current.value,
                provincia: this.provinciaRef.current.value,
                email: this.emailRef.current.value,
                f_nacimiento: this.fNacimientoRef.current.value,

            }

        });


    }

    getProvinces = ()=>{

        axios.get(this.url+'/provinces')
        .then(res=>{

            this.setState({

                provinces: res.data.provinces

            })

        });

    }

    saveContact = (event) =>{

        event.preventDefault();

        // Rellenar el state con los datos del formulario
        this.changeState();

        // Comprobamos si los datos son validos
        if (this.validator.allValid()){

            // Hacer una petición http por POST para guardar los datos del contacto
            axios.post(this.url+'save', this.state.contact)

            .then(res => {

                if(res.data.contact){

                    this.setState({
                        contact: res.data.contact,
                        status: 'success'
                    })

                }else{

                    this.setState({
                        status: 'failed'
                    });

                }

            })
        }else{

            this.setState({
                status: 'failed'
            });

            // Si la validación falla mostramos los mensajes
            this.validator.showMessages();

        }

    }

    render(){

        if(this.state.status==='success'){

            return <Navigate to="/contactos" />;

        }

        var listProvinces = this.state.provinces.map((province, index)=>{

            return(

                <option key={index}>{province.nombre}</option>

            );
    
        });

        return(

            <section id="content">

                <h1 className="subheader">NUEVO CONTACTO</h1>

                <form className="mid-form" onSubmit={this.saveContact}>

                    <div className="form-group">
                        <label htmlFor="nombre">Nombre</label>
                        <input type="text" name="nombre" ref={this.nombreRef} onChange={this.changeState}
                                onBlur={()=>this.validator.showMessageFor('nombre')}
                                onKeyPress={()=>this.validator.showMessageFor('nombre')} />
                        <small>
                            {this.validator.message('nombre', this.state.contact.nombre, 'required')}
                        </small>
                    </div>

                    <div className="form-group">
                        <label htmlFor="apellidos">Apellidos</label>
                        <input type="text" name="apellidos" ref={this.apellidosRef} onChange={this.changeState}
                                onBlur={()=>this.validator.showMessageFor('apellidos')}
                                onKeyPress={()=>this.validator.showMessageFor('apellidos')} />
                        <small>
                            {this.validator.message('apellidos', this.state.contact.apellidos, 'required')}
                        </small>
                    </div>

                    <div className="form-group">
                        <label htmlFor="movil">Móvil</label>
                        <input type="tel" name="movil" ref={this.movilRef} onChange={this.changeState}
                                onBlur={()=>this.validator.showMessageFor('movil')}
                                onKeyPress={()=>this.validator.showMessageFor('movil')} />
                        <small className="msg-validator">
                            {this.validator.message('movil', this.state.contact.movil, 'required|movil')}
                        </small>
                    </div>

                    <div className="form-group">
                        <label htmlFor="direccion">Dirección</label>
                        <input type="text" name="direccion" ref={this.direccionRef} onChange={this.changeState} />
                    </div>

                    <div className="form-group">
                        <label htmlFor="poblacion">Población</label>
                        <input type="text" name="poblacion" ref={this.poblacionRef} onChange={this.changeState} />
                    </div>

                    <div className="form-group">
                        <label htmlFor="c_postal">Código Postal</label>
                        <input type="text" name="c_postal" ref={this.cPostalRef} onChange={this.changeState}
                                onBlur={()=>this.validator.showMessageFor('c_postal')}
                                onKeyPress={()=>this.validator.showMessageFor('c_postal')} />
                        <small>
                            {this.validator.message('c_postal', this.state.contact.c_postal, 'required|c_postal')}
                        </small>
                    </div>

                    <div className="form-group">
                        <label htmlFor="provincia">Provincia</label>
                        <select name="provincia" ref={this.provinciaRef} onChange={this.changeState}>
                            <option value="">----- Selecciona Provincia -----</option>
                            {listProvinces}
                        </select>
                    </div>

                    <div className="form-group">
                        <label htmlFor="email">Email</label>
                        <input type="email" name="email" ref={this.emailRef} onChange={this.changeState}
                                onBlur={()=>this.validator.showMessageFor('email')}
                                onKeyPress={()=>this.validator.showMessageFor('email')} />
                        <small>
                            {this.validator.message('email', this.state.contact.email, 'required|email')}
                        </small>
                    </div>

                    <div className="form-group">
                        <label htmlFor="f_nacimiento">Fecha Nacimiento</label>
                        <input type="date" name="f_nacimiento" defaultValue={moment().format('YYYY-MM-DD')} ref={this.fNacimientoRef}
                                onChange={()=> {this.changeState(); this.validator.showMessageFor('f_nacimiento')}}
                                onBlur={()=>this.validator.showMessageFor('f_nacimiento')} />
                        <small>
                            {this.validator.message('f_nacimiento', this.state.contact.f_nacimiento, 'required')}
                        </small>
                    </div>

                    {/* LIMPIAR FLOTADOS */}
                    <div className="clearfix"></div>

                    <input type="submit" value="Guardar" className="btn btn-success" />

                </form>

            </section>

        );

    }

}

export default NewContact;

// Vue/src/components/NewContact.vue
<template>

    <section id="content">

        <h1 class="subheader">NUEVO CONTACTO</h1>

        <form class="mid-form" v-on:submit.prevent="saveContact()">

            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" v-model="v$.contact.nombre.$model" @blur="v$.contact.nombre.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.nombre.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="apellidos">Apellidos</label>
                <input type="text" name="apellidos" v-model="v$.contact.apellidos.$model" @blur="v$.contact.apellidos.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.apellidos.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="movil">Móvil</label>
                <input type="tel" name="movil" v-model="v$.contact.movil.$model" @blur="v$.contact.movil.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.movil.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="direccion">Dirección</label>
                <input type="text" name="direccion" v-model="contact.direccion" />
            </div>

            <div class="form-group">
                <label for="poblacion">Población</label>
                <input type="text" name="poblacion" v-model="contact.poblacion" />
            </div>

            <div class="form-group">
                <label for="c_postal">Código Postal</label>
                <input type="text" name="c_postal" v-model="v$.contact.c_postal.$model" @blur="v$.contact.c_postal.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.c_postal.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="provincia">Provincia</label>
                <select name="provincia" v-model="contact.provincia">
                    <option value="">----- Selecciona Provincia -----</option>
                    <option v-for="province, index in provinces" :key="index">{{ province.nombre }}</option>
                </select>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" v-model="v$.contact.email.$model" @blur="v$.contact.email.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.email.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="f_nacimiento">Fecha Nacimiento</label>
                <input type="date" name="f_nacimiento" v-model="v$.contact.f_nacimiento.$model" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.f_nacimiento.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <!-- LIMPIAR FLOTADOS -->
            <div class="clearfix"></div>

            <input type="submit" value="Guardar" class="btn btn-success" />

        </form>

    </section>
    
</template>

<script>

import axios from 'axios';
import Global from '../Global';
import useVuelidate from '@vuelidate/core';
import {required, email, helpers} from '@vuelidate/validators';
import Contact from '../models/ContactModel';
import moment from 'moment';

export default {
    name: 'NewContactComponent',
    data(){

        return{
            v$: useVuelidate(),
            moment: moment,
            contact: new Contact('','','','','','','','',moment().format('YYYY-MM-DD')),
            provinces: [],
            url: Global.url
        }

    },
    mounted(){

        this.getProvinces();

    },
    validations: {
        
        contact: {

            nombre: {
                required: helpers.withMessage('El campo Nombre es requerido', required)
            },
            apellidos: {
                required: helpers.withMessage('El campo Apellidos es requerido', required)
            },
            movil: {
                required: helpers.withMessage('El campo Móvil es requerido', required),
                movil: helpers.withMessage('El Móvil introducido no es válido',
                       helpers.regex(/^[6|7]{1}[0-9]{8}$/))
            },
            email: {
                required: helpers.withMessage('El campo Email es requerido', required),
                email: helpers.withMessage('El Email introducido no es válido', email)
            },
            c_postal: {
                required: helpers.withMessage('El campo Código Postal es requerido', required),
                c_postal: helpers.withMessage('El Código Postal introducido no es válido',
                          helpers.regex(/^(5[0-2]{1}|[0-4]{1}\d{1})\d{3}$/))
            },
            f_nacimiento: {
                required: helpers.withMessage('La Fecha de Nacimiento es requerida', required),
            }

        }

    },
    methods: {

        getProvinces(){

            axios.get(this.url +'provinces')
            .then(res=>{

                if(res.data.status==='success'){

                    this.provinces = res.data.provinces;

                }

            });

        },
        saveContact(){

            this.v$.$touch();

            // Comprobamos si los datos son validos
            if(this.v$.$invalid){

                return false;

            }else{

                // Hacer una petición http por POST para guardar los datos del contacto
                axios.post(this.url+'save', this.contact)

                .then(res => {

                    if(res.data.status === 'success'){

                        this.$router.push('/contactos');

                    }

                })
                .catch(error =>{

                    console.log(error);

                });
            }

        }

    }

}

</script>
