// Angular/src/app/components/new-contact/new-contact.component.ts
import { Component, OnInit } from '@angular/core';
import { ContactService } from 'src/app/services/contact.service';
import { ProvinceService } from 'src/app/services/province.service';
import { Router} from '@angular/router';
import { Contact } from '../../models/contact';
import { Province } from '../../models/province';

@Component({
  selector: 'app-new-contact',
  templateUrl: './new-contact.component.html',
  styleUrls: ['./new-contact.component.css'],
  providers: [ContactService, ProvinceService]
})
export class NewContactComponent implements OnInit {

  public page_title: String;
  public today: Date;
  public contact: Contact;
  public provinces: Province[];

  constructor(
    private _contactService: ContactService,
    private _provinceService: ProvinceService,
    private _router: Router,
  ){
    this.page_title = "Nuevo Contacto";
    this.today = new Date();
    this.contact= new Contact('', '', '', 0, '', '', 0, '', '', new Date());
    this.provinces = [];
  }

  ngOnInit(): void {

    this.getProvinces();

  }

  getProvinces(){

    this._provinceService.getProvinces().subscribe(

      response=>{

        if (response.provinces){

          this.provinces = response.provinces;

        }

      },
      error=>{

        console.log(error);

      }

    );

  }

  onSubmit(){

    this._contactService.create(this.contact).subscribe(
      
      response=>{

        if (response.contact){

          this.contact = response.contact;
          this._router.navigate(["contactos"]);

        }

      },
      error=>{

        console.log(error);

      }

    );

  }

}

<section id="content">

    <h1 class="subheader">{{page_title}}</h1>

    <form class="mid-form" #contactForm="ngForm" (ngSubmit)="contactForm.valid && onSubmit()" novalidate>

        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="contact.nombre" required/>
            <small class="msg-validator" *ngIf="!nombre.valid && (nombre.dirty || nombre.touched || contactForm.submitted)">El nombre es requerido</small>
        </div>

        <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="contact.apellidos" required/>
            <small class="msg-validator" *ngIf="!apellidos.valid && (apellidos.dirty || apellidos.touched || contactForm.submitted)">Los apellidos son requeridos</small>
        </div>

        <div class="form-group">
            <label for="movil">Móvil</label>
            <input type="tel" name="movil" #movil="ngModel" [(ngModel)]="contact.movil" pattern="[6|7]{1}[0-9]{8}" required/>
            <small class="msg-validator" *ngIf="!movil.valid && (movil.dirty || movil.touched || contactForm.submitted)">El número de móvil no es válido</small>
        </div>

        <div class="form-group">
            <label for="direccion">Dirección</label>
            <input type="text" name="direccion" [(ngModel)]="contact.direccion" />
        </div>

        <div class="form-group">
            <label for="poblacion">Población</label>
            <input type="text" name="poblacion" [(ngModel)]="contact.poblacion" />
        </div>

        <div class="form-group">
            <label for="c_postal">Código Postal</label>
            <input type="text" name="c_postal" #c_postal="ngModel" [(ngModel)]="contact.c_postal" pattern="^(5[0-2]{1}|[0-4]{1}\d{1})\d{3}$" ngRequired/>
            <small class="msg-validator" *ngIf="!c_postal.valid && (c_postal.dirty || c_postal.touched || contactForm.submitted)">El código postal no es válido</small>
        </div>

        <div class="form-group">
            <label for="provincia" >Provincia</label>
            <select name="provincia" [(ngModel)]="contact.provincia">
                <option value="">----- Selecciona Provincia -----</option>
                <option *ngFor="let province of provinces">{{province.nombre}}</option>
            </select>
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" #email="ngModel" [(ngModel)]="contact.email"
                   pattern="^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required
            />
            <small class="msg-validator" *ngIf="!email.valid && (email.dirty || email.touched || contactForm.submitted)">El email no es válido</small>
        </div>

        <div class="form-group">
            <label for="f_nacimiento">Fecha Nacimiento</label>
            <input type="date" name="f_nacimiento" #f_nacimiento="ngModel" [ngModel]="contact.f_nacimiento | date: 'YYYY-MM-dd'" (ngModelChange)="contact.f_nacimiento = $event"
                [max]="today | date: 'YYYY-MM-dd'" required />
            <small class="msg-validator" *ngIf="!f_nacimiento.valid && (f_nacimiento.dirty || f_nacimiento.touched || contactForm.submitted)">La Fecha de Nacimiento no es válida</small>
        </div>

        <!-- LIMPIAR FLOTADOS -->
        <div class="clearfix"></div>

        <input type="submit" value="Guardar" class="btn btn-success" />

    </form>

  </section>

// Vue/src/components/NewContact.vue
<template>

    <section id="content">

        <h1 class="subheader">NUEVO CONTACTO</h1>

        <form class="mid-form" v-on:submit.prevent="saveContact()">

            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" v-model="v$.contact.nombre.$model" @blur="v$.contact.nombre.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.nombre.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="apellidos">Apellidos</label>
                <input type="text" name="apellidos" v-model="v$.contact.apellidos.$model" @blur="v$.contact.apellidos.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.apellidos.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="movil">Móvil</label>
                <input type="tel" name="movil" v-model="v$.contact.movil.$model" @blur="v$.contact.movil.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.movil.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="direccion">Dirección</label>
                <input type="text" name="direccion" v-model="contact.direccion" />
            </div>

            <div class="form-group">
                <label for="poblacion">Población</label>
                <input type="text" name="poblacion" v-model="contact.poblacion" />
            </div>

            <div class="form-group">
                <label for="c_postal">Código Postal</label>
                <input type="text" name="c_postal" v-model="v$.contact.c_postal.$model" @blur="v$.contact.c_postal.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.c_postal.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="provincia">Provincia</label>
                <select name="provincia" v-model="contact.provincia">
                    <option value="">----- Selecciona Provincia -----</option>
                    <option v-for="province, index in provinces" :key="index">{{ province.nombre }}</option>
                </select>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" v-model="v$.contact.email.$model" @blur="v$.contact.email.$touch" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.email.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <div class="form-group">
                <label for="f_nacimiento">Fecha Nacimiento</label>
                <input type="date" name="f_nacimiento" v-model="v$.contact.f_nacimiento.$model" />
                <small class="msg-validator" v-for="(error, index) in v$.contact.f_nacimiento.$errors" :key="index">
                    {{ error.$message }}
                </small>
            </div>

            <!-- LIMPIAR FLOTADOS -->
            <div class="clearfix"></div>

            <input type="submit" value="Guardar" class="btn btn-success" />

        </form>

    </section>
    
</template>

<script>

import axios from 'axios';
import Global from '../Global';
import useVuelidate from '@vuelidate/core';
import {required, email, helpers} from '@vuelidate/validators';
import Contact from '../models/ContactModel';
import moment from 'moment';

export default {
    name: 'NewContactComponent',
    data(){

        return{
            v$: useVuelidate(),
            moment: moment,
            contact: new Contact('','','','','','','','',moment().format('YYYY-MM-DD')),
            provinces: [],
            url: Global.url
        }

    },
    mounted(){

        this.getProvinces();

    },
    validations: {
        
        contact: {

            nombre: {
                required: helpers.withMessage('El campo Nombre es requerido', required)
            },
            apellidos: {
                required: helpers.withMessage('El campo Apellidos es requerido', required)
            },
            movil: {
                required: helpers.withMessage('El campo Móvil es requerido', required),
                movil: helpers.withMessage('El Móvil introducido no es válido',
                       helpers.regex(/^[6|7]{1}[0-9]{8}$/))
            },
            email: {
                required: helpers.withMessage('El campo Email es requerido', required),
                email: helpers.withMessage('El Email introducido no es válido', email)
            },
            c_postal: {
                required: helpers.withMessage('El campo Código Postal es requerido', required),
                c_postal: helpers.withMessage('El Código Postal introducido no es válido',
                          helpers.regex(/^(5[0-2]{1}|[0-4]{1}\d{1})\d{3}$/))
            },
            f_nacimiento: {
                required: helpers.withMessage('La Fecha de Nacimiento es requerida', required),
            }

        }

    },
    methods: {

        getProvinces(){

            axios.get(this.url +'provinces')
            .then(res=>{

                if(res.data.status==='success'){

                    this.provinces = res.data.provinces;

                }

            });

        },
        saveContact(){

            this.v$.$touch();

            // Comprobamos si los datos son validos
            if(this.v$.$invalid){

                return false;

            }else{

                // Hacer una petición http por POST para guardar los datos del contacto
                axios.post(this.url+'save', this.contact)

                .then(res => {

                    if(res.data.status === 'success'){

                        this.$router.push('/contactos');

                    }

                })
                .catch(error =>{

                    console.log(error);

                });
            }

        }

    }

}

</script>
