// React/src/components/Slider.js
import React, {Component} from 'react';
import {NavLink} from 'react-router-dom';

class Slider extends Component{

    render(){

        return(

            <div id="slider" className="slider">

                {/* MENU */}

                <nav id="menu">
                    <ul>
                        <li><NavLink to="/">Cumpleaños</NavLink></li>
                        <li><NavLink to="/contactos">Contactos</NavLink></li>
                    </ul>
                </nav>

            </div>

        );

    }

}

export default Slider;

// Vue/src/components/Slider.vue
<template>

    <div id="slider" className="slider">

        <!--* MENU -->

        <nav id="menu">
            <ul>
                <li><router-link to="/home">Cumpleaños</router-link></li>
                <li><router-link to="/contactos">Contactos</router-link></li>
            </ul>
        </nav>

    </div>
    
</template>

<script>

export default {
    name: 'SliderComponent'
}

</script>
