// Vue/src/components/Sidebar.vue
<template>

    <aside id="sidebar">

        <div id="nav-blog" class="sidebar-item">
            <h3>Puedes hacer esto</h3>
            <router-link to="/nuevo-contacto" class="btn btn-success">Añadir contacto</router-link>
        </div>

        <div id="search" class="sidebar-item">
            <h3>Buscador</h3>
            <p>Encuentra al contacto que buscas</p>
            <form @submit.prevent="search">
                <div class="form-group">
                    <label htmlFor="title">Nombre</label>
                    <input type="text" name="nombre" v-model="nombre" />
                </div>
                <div className="form-group">
                    <label htmlFor="title">Apellidos</label>
                    <input type="text" name="apellidos" v-model="apellidos" />
                </div>
                <input type="submit" name="submit" value="Buscar" className="btn btn-success"/>
            </form>
        </div>

    </aside>
    
</template>

<script>

export default {
    name: 'SidebarComponent',
    data(){

        return {
            nombre: null,
            apellidos: null
        }

    },
    methods: {

        search(){

            if(this.nombre && this.apellidos){

                this.$router.push('/buscar?nombre='+this.nombre+'&apellidos='+this.apellidos);
      
            }else if(this.nombre){

                this.$router.push('/buscar?nombre='+this.nombre);

            }else if(this.apellidos){

                this.$router.push('/buscar?apellidos='+this.apellidos);

            }

        }

    }
}

</script>

// Angular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css'],
})
export class SidebarComponent implements OnInit {

  public searchNombre!: string;
  public searchApellidos!: string;

  constructor(
    private _router: Router
  ){}

  ngOnInit(): void {
  }

  goSearch(){

    if(this.searchNombre && this.searchApellidos){

      this._router.navigate(['/buscar'], {queryParams: {nombre: this.searchNombre, apellidos: this.searchApellidos}});
      
    }else if(this.searchNombre){

      this._router.navigate(['/buscar'], {queryParams: {nombre: this.searchNombre}});

    }else if(this.searchApellidos){

      this._router.navigate(['/buscar'], {queryParams: {apellidos: this.searchApellidos}});

    }

  }

}

<aside id="sidebar">

    <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a [routerLink]="['/nuevo-contacto']" class="btn btn-success">Añadir contacto</a>
    </div>

    <div id="search" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra al contacto que buscas</p>
        <form #searchForm="ngForm" (ngSubmit)="goSearch()">
            <div class="form-group">
                <label for="title">Nombre</label>
                <input type="text" name="nombre" [(ngModel)]="searchNombre" />
            </div>
            <div class="form-group">
                <label for="title">Apellidos</label>
                <input type="text" name="apellidos" [(ngModel)]="searchApellidos" />
            </div>
            <input type="submit" name="submit" value="Buscar" class="btn btn-success"/>
        </form>
    </div>

</aside>
