// React/src/components/Contact.js
import React, {Component} from 'react';
import axios from 'axios';
import Moment from 'react-moment';
import swal from "sweetalert";
import Global from '../Global';
import {Link, Navigate, useParams} from 'react-router-dom';

class Contact extends Component{

    url = Global.url;

    state = {
        contact: false,
        status: null
    }

    componentDidMount(){

        this.getContact();

    }

    getContact = ()=>{

        var id = this.props.contactId;

        axios.get(this.url+'contact/'+id)

        .then(res=> {

            this.setState({

                contact: res.data.contact,
                status: 'success'

            });
        })

    }

    delete = (contactId)=>{

        swal({
            title: "¿Estás seguro?",
            text: "Una vez borrado no podras recuperarlo!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })

        .then((willDelete)=> {

            if(willDelete) {

                axios.delete(this.url+ 'contact/'+ contactId)
                .then(res=> {
    
                    this.setState({
    
                        article: res.data.contact,
                        status: 'delete'
    
                    });
                    
                });
                
                swal(
                    "Contacto borrado",
                    "El contacto ha sido borrado correctamente",
                    "success"
                );

            }else{

                swal(
                    "Tranquilo!!",
                    "El contacto no ha sido borrado",
                    "success"
                );

            }

    });

    }

    render(){

        var contact = this.state.contact;

        if(this.state.status==='delete'){

            return <Navigate to={'/contactos'} />;

        }

        return(

            <section id="content">

                <h2 className="subheader">CONTACTO</h2>

                <table id="tabla_contacto" className="center">

                    <tbody>
                        <tr>
                            <th>Nombre</th>
                            <td>{contact.nombre}</td>
                        </tr>

                        <tr>
                            <th>Apellidos</th>
                            <td>{contact.apellidos}</td>
                        </tr>
                        <tr>
                            <th>Móvil</th>
                            <td>{contact.movil}</td>
                        </tr>
                        <tr>
                            <th>Dirección</th>
                            <td>{contact.direccion}</td>
                        </tr>
                        <tr>
                            <th>Población</th>
                            <td>{contact.poblacion}</td>
                        </tr>
                        <tr>
                            <th>Código Postal</th>
                            <td>{contact.c_postal}</td>
                        </tr>
                        <tr>
                            <th>Provincia</th>
                            <td>{contact.provincia}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{contact.email}</td>
                        </tr>
                        <tr>
                            <th>Fecha Nacimiento</th>
                            <td><Moment format="DD/MM/YYYY">{contact.f_nacimiento}</Moment></td>
                        </tr>
                    </tbody>

                </table>

                <div className="buttons">
                    <Link to={'/contacto/editar/'+contact._id} className="btn btn-warning">Editar</Link>
                    <button className="btn btn-danger" onClick={()=>{this.delete(contact._id)}}>Borrar</button>
                </div>

            </section>

        );

    }
    

}

function ContactId(){

    let {id} = useParams();

    return <Contact contactId={id} />

}

export default ContactId;

// Angular/src/app/components/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';
import { ContactService } from 'src/app/services/contact.service';
import { Router, ActivatedRoute } from '@angular/router';
import { Contact } from 'src/app/models/contact';
import swal from 'sweetalert';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css'],
  providers: [ContactService]
})

export class ContactComponent implements OnInit {

  public contact!: Contact;

  constructor(
    private _contactService: ContactService,
    private _route: ActivatedRoute,
    private _router: Router,
  ){
  }

  ngOnInit(): void {

    this._route.params.subscribe(params=>{

      let id = params['id'];

      this._contactService.getContact(id).subscribe(
        response=>{
          
          if (response.contact){

            this.contact = response.contact;

          }
  
        },
        error=>{
  
          console.log(error);
  
        }
      );

    });
    
  }

  delete(contactId: String){

    swal({
      title: "¿Estás seguro de borrar el contacto?",
      text: "¡Una vez borrado no podrás recuperarlo!",
      buttons: [true, true],
      dangerMode: true
    })
    .then((willDelete) => {
      if (willDelete){

        this._contactService.delete(contactId).subscribe(

          response=>{
    
            swal("¡El contacto ha sido borrado correctamente!", {
              icon: "success",
            });

            this.contact = response.contact;
            this._router.navigate(["contactos"]);
    
          },
          error=>{
    
            console.log(error);
            this._router.navigate(["contactos"]);
            
          }
        );

      } else {
        swal("¡Tranquilo nada se ha borrado!");
      }
    });


  }

}

<section id="content" *ngIf="contact">

    <h2 class="subheader">CONTACTO</h2>

    <table id="tabla_contacto" class="center">

        <tr>
            <th>Nombre</th>
            <td>{{contact.nombre}}</td>
        </tr>

        <tr>
            <th>Apellidos</th>
            <td>{{contact.apellidos}}</td>
        </tr>
        <tr>
            <th>Móvil</th>
            <td>{{contact.movil}}</td>
        </tr>
        <tr>
            <th>Dirección</th>
            <td>{{contact.direccion}}</td>
        </tr>
        <tr>
            <th>Población</th>
            <td>{{contact.poblacion}}</td>
        </tr>
        <tr>
            <th>Código Postal</th>
            <td>{{contact.c_postal}}</td>
        </tr>
        <tr>
            <th>Provincia</th>
            <td>{{contact.provincia}}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{contact.email}}</td>
        </tr>
        <tr>
            <th>Fecha Nacimiento</th>
            <td>{{contact.f_nacimiento | date:'dd/MM/yyyy'}}</td>
        </tr>

    </table>

        <div class="buttons">
            <a [routerLink]="['/contacto/editar', contact._id]" class="btn btn-warning">Editar</a>
            <a (click)="delete(contact._id)" class="btn btn-danger">Borrar</a>
        </div>

</section>
